# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Groovy cluster

on:
  push:
  pull_request:

jobs:
  test-groovy-modules:
    runs-on: ubuntu-18.04
    name: Test groovy modules
    env:
      DISPLAY: ":99.0"
      OPTS: -Dmetabuild.jsonurl=https://raw.githubusercontent.com/apache/netbeans-jenkins-lib/master/meta/netbeansrelease.json -Dcluster.config=groovy -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false -Dtest-unit-sys-prop.ignore.random.failures=true
      TEST_OPTS: -Dtest.run.args=--limit-modules=java.base,java.logging,java.xml,java.prefs,java.desktop,java.management,java.instrument,jdk.zipfs,java.scripting,java.naming -Dtest.bootclasspath.prepend.args=-Dno.netbeans.bootclasspath.prepend.needed=true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # OpenJDK 8 is used for build
      - name: Setup OpenJDK 8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 8

      - name: Caching dependencies
        uses: actions/cache@v2
        with:
          path: ~/.hgexternalcache
          key: ${{ runner.os }}-${{ hashFiles('**/external/binaries-list') }}
          restore-keys: ${{ runner.os }}-

      - name: Launch Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Clean
        run: ant $OPTS -quiet clean

      - name: Build
        run: ant $OPTS -quiet build

#      - name: Test on OpenJDK 8
#        run: |
#          # ant $OPTS -f groovy/groovy test
#          # ant $OPTS -f groovy/groovy.java test
#          ant $OPTS -f groovy/groovy.editor test
#          ant $OPTS -f groovy/groovy.gsp test
#          # ant $OPTS -f groovy/groovy.kit test
#          ant $OPTS -f groovy/groovy.support test

      - name: Setup OpenJDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 11
          targets: 'JDK_11'

      - name: Test on OpenJDK 11
        run: |
          # ant $OPTS -f groovy/groovy test
          # ant $OPTS -f groovy/groovy.java test
          ant $TEST_OPTS -Dtest.nbjdk.home=$JDK_11 -f groovy/groovy.editor test
          ant $TEST_OPTS -Dtest.nbjdk.home=$JDK_11 -f groovy/groovy.gsp test
          # ant $OPTS -f groovy/groovy.kit test
          ant $TEST_OPTS -Dtest.nbjdk.home=$JDK_11 -f groovy/groovy.support test

      - name: Setup OpenJDK 14
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 14
          targets: 'JDK_14'

      - name: Test on OpenJDK 14
        run: |
          # ant $OPTS -f groovy/groovy test
          # ant $OPTS -f groovy/groovy.java test
          ant $OPTS -Dtest.nbjdk.home=$JDK_14 -f groovy/groovy.editor test
          ant $OPTS -Dtest.nbjdk.home=$JDK_14 -f groovy/groovy.gsp test
          # ant $OPTS -f groovy/groovy.kit test
          ant $OPTS -Dtest.nbjdk.home=$JDK_14 -f groovy/groovy.support test

      - name: Setup OpenJDK 15
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 15
          targets: 'JDK_15'

      - name: Test on OpenJDK 15
        run: |
          # ant $OPTS -f groovy/groovy test
          # ant $OPTS -f groovy/groovy.java test
          ant $OPTS -Dtest.nbjdk.home=$JDK_15 -f groovy/groovy.editor test
          ant $OPTS -Dtest.nbjdk.home=$JDK_15 -f groovy/groovy.gsp test
          # ant $OPTS -f groovy/groovy.kit test
          ant $OPTS -Dtest.nbjdk.home=$JDK_15 -f groovy/groovy.support test
